leftnav:
- identifier: dd78535f-ec9b-7575-25f5-9a1d0fcc38e9
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e7a25f8a-6b5c-0280-a9f5-2b7e7b93de0e
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 8a66fc92-7c07-b421-b2f4-92e3ea746ffb
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 1db2370c-ab7c-4f2a-1ebf-3aa017ec039a
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: e84bbdf7-a3f7-2df4-2601-cb401ce23eb3
  name: Exams
  pageRef: /pages/exams
  weight: 50
